(() => {
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),intro=document.getElementById('intro');
const startButton=document.getElementById('startButton'),blueMeter=document.getElementById('blueEvidence'),greenMeter=document.getElementById('greenEvidence'),blueValue=document.getElementById('blueValue'),greenValue=document.getElementById('greenValue'),neuralState=document.getElementById('neuralState'),lastEvent=document.getElementById('lastEvent');
const W=canvas.width,H=canvas.height,keys=new Set(),TAU=Math.PI*2;
const cfg={blueHz:10,greenHz:12,evidenceRate:.78,evidenceDecay:.52,threshold:.84,sightDuration:3.4,guardDuration:3.4,sightMultiplier:1.65,guardHealPerSecond:4.2,orbAngularSpeed:.92,orbRadiusX:116,orbRadiusY:56};
const state={started:false,t:0,lastShot:-99,lastDash:-99,blueEvidence:0,greenEvidence:0,sightUntil:0,guardUntil:0,bciTarget:null,particles:[],shots:[],enemyShots:[]};
const player={x:W*.24,y:H*.56,r:18,hp:100,maxHp:100,dashUntil:0};
const boss={x:W*.72,y:H*.48,r:62,hp:800,maxHp:800,phase:1,alive:true,shotClock:0};
const clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v));
function emitParticle(x,y,kind,n=10){for(let i=0;i<n;i++){const a=Math.random()*TAU,s=35+Math.random()*120;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.45,max:.8,kind});}}
function applyAura(target,confidence=1,quality=1){if(!state.started||!boss.alive)return;if(confidence<.55||quality<.55){lastEvent.textContent=`ABSTAIN ${target??''}`;neuralState.textContent='UNCERTAIN';return;}if(target==='sight'){state.sightUntil=Math.max(state.sightUntil,state.t+cfg.sightDuration);state.blueEvidence=0;emitParticle(boss.x,boss.y,'blue',34);lastEvent.textContent=`SIGHT ${confidence.toFixed(2)}`;neuralState.textContent='NEURAL SIGHT';}else if(target==='guard'){state.guardUntil=Math.max(state.guardUntil,state.t+cfg.guardDuration);state.greenEvidence=0;emitParticle(player.x,player.y,'green',34);lastEvent.textContent=`GUARD ${confidence.toFixed(2)}`;neuralState.textContent='NEURAL GUARD';}}
window.addEventListener('mindforge-neural-event',e=>{const d=e.detail||{};if(d.event==='AURA_SELECTED')applyAura(d.target,Number(d.confidence??0),Number(d.quality??0));if(d.event==='ABSTAIN'){neuralState.textContent='ABSTAIN';lastEvent.textContent=d.reason||'ABSTAIN';}});
function updateEvidence(dt){const b=keys.has('q'),g=keys.has('e');if(b&&!g){state.blueEvidence=clamp(state.blueEvidence+cfg.evidenceRate*dt,0,1);state.greenEvidence=clamp(state.greenEvidence-cfg.evidenceDecay*dt,0,1);state.bciTarget='sight';}else if(g&&!b){state.greenEvidence=clamp(state.greenEvidence+cfg.evidenceRate*dt,0,1);state.blueEvidence=clamp(state.blueEvidence-cfg.evidenceDecay*dt,0,1);state.bciTarget='guard';}else{state.blueEvidence=clamp(state.blueEvidence-cfg.evidenceDecay*dt,0,1);state.greenEvidence=clamp(state.greenEvidence-cfg.evidenceDecay*dt,0,1);state.bciTarget=null;}if(state.blueEvidence>=cfg.threshold)applyAura('sight',.90,.92);if(state.greenEvidence>=cfg.threshold)applyAura('guard',.90,.92);}
function shoot(){if(state.t-state.lastShot<.23||!boss.alive)return;state.lastShot=state.t;const dx=boss.x-player.x,dy=boss.y-player.y,m=Math.hypot(dx,dy)||1;state.shots.push({x:player.x,y:player.y,vx:dx/m*700,vy:dy/m*700,life:1.4});}
function dash(){if(state.t-state.lastDash<1.2)return;state.lastDash=state.t;player.dashUntil=state.t+.18;emitParticle(player.x,player.y,'white',14);}
function updatePlayer(dt){let dx=(keys.has('d')?1:0)-(keys.has('a')?1:0),dy=(keys.has('s')?1:0)-(keys.has('w')?1:0),m=Math.hypot(dx,dy)||1,speed=state.t<player.dashUntil?600:260;if(dx||dy){dx/=m;dy/=m;}player.x=clamp(player.x+dx*speed*dt,38,W-38);player.y=clamp(player.y+dy*speed*dt,56,H-44);if(keys.has(' '))shoot();if(state.t<state.guardUntil)player.hp=clamp(player.hp+cfg.guardHealPerSecond*dt,0,player.maxHp);}
function updateBoss(dt){if(!boss.alive)return;boss.phase=boss.hp>boss.maxHp*.66?1:boss.hp>boss.maxHp*.33?2:3;boss.shotClock-=dt;if(boss.shotClock<=0){boss.shotClock=[0,1.1,.78,.52][boss.phase];for(let i=0;i<boss.phase;i++){const aim=Math.atan2(player.y-boss.y,player.x-boss.x)+(i-(boss.phase-1)/2)*.22;state.enemyShots.push({x:boss.x,y:boss.y,vx:Math.cos(aim)*(250+boss.phase*25),vy:Math.sin(aim)*(250+boss.phase*25),r:8,life:4});}}}
function updateProjectiles(dt){for(const s of state.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(boss.alive&&s.life>0&&(s.x-boss.x)**2+(s.y-boss.y)**2<(boss.r+5)**2){const damage=18*(state.t<state.sightUntil?cfg.sightMultiplier:1);boss.hp=Math.max(0,boss.hp-damage);s.life=0;emitParticle(s.x,s.y,state.t<state.sightUntil?'blue':'white',8);if(boss.hp<=0){boss.alive=false;emitParticle(boss.x,boss.y,'blue',90);}}}for(const s of state.enemyShots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.life>0&&(s.x-player.x)**2+(s.y-player.y)**2<(s.r+player.r)**2&&state.t>=player.dashUntil){player.hp=Math.max(0,player.hp-10);s.life=0;emitParticle(player.x,player.y,'red',12);}}state.shots=state.shots.filter(s=>s.life>0);state.enemyShots=state.enemyShots.filter(s=>s.life>0);}
function updateParticles(dt){for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97;p.life-=dt;}state.particles=state.particles.filter(p=>p.life>0);}
function auraPosition(kind){const phase=state.t*cfg.orbAngularSpeed+(kind==='guard'?Math.PI:0);return{x:boss.x+Math.cos(phase)*cfg.orbRadiusX,y:boss.y+Math.sin(phase)*cfg.orbRadiusY};}
function drawBackground(){const g=ctx.createRadialGradient(W*.55,H*.45,20,W*.55,H*.45,W*.65);g.addColorStop(0,'#171a36');g.addColorStop(1,'#050710');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(140,150,220,.10)';for(let x=0;x<W;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}}
function drawWisp(){const active=boss.alive&&state.started,wx=active?player.x+(boss.x-player.x)*.18:player.x+42+Math.sin(state.t*2.2)*8,wy=active?player.y-55:player.y-44+Math.cos(state.t*1.9)*8;ctx.save();ctx.globalCompositeOperation='lighter';const glow=ctx.createRadialGradient(wx,wy,0,wx,wy,30);glow.addColorStop(0,'rgba(241,242,255,.95)');glow.addColorStop(.35,'rgba(160,170,255,.45)');glow.addColorStop(1,'rgba(120,130,255,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(wx,wy,30,0,TAU);ctx.fill();ctx.restore();}
function drawAura(target,color,hz,pos,activeUntil,evidence){const phase=Math.sin(TAU*hz*state.t),mod=.52+.48*(phase*.5+.5),active=state.t<activeUntil,r=24+9*mod+(active?7:0),rgb=color==='blue'?'75,154,255':'69,239,154';ctx.save();ctx.globalCompositeOperation='lighter';const grad=ctx.createRadialGradient(pos.x,pos.y,2,pos.x,pos.y,r*1.9);grad.addColorStop(0,`rgba(${rgb},${.88*mod+.12})`);grad.addColorStop(.34,`rgba(${rgb},${.45*mod})`);grad.addColorStop(1,`rgba(${rgb},0)`);ctx.fillStyle=grad;ctx.beginPath();ctx.arc(pos.x,pos.y,r*1.9,0,TAU);ctx.fill();ctx.strokeStyle=`rgba(${rgb},${.55+.4*mod})`;ctx.lineWidth=active?5:3;ctx.beginPath();ctx.arc(pos.x,pos.y,r,0,TAU);ctx.stroke();ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=2;if(target==='sight'){ctx.beginPath();ctx.moveTo(pos.x,pos.y-13);ctx.lineTo(pos.x+11,pos.y+9);ctx.lineTo(pos.x-11,pos.y+9);ctx.closePath();ctx.stroke();}else{ctx.beginPath();ctx.arc(pos.x,pos.y,11,0,TAU);ctx.stroke();ctx.beginPath();ctx.moveTo(pos.x-7,pos.y);ctx.lineTo(pos.x+7,pos.y);ctx.moveTo(pos.x,pos.y-7);ctx.lineTo(pos.x,pos.y+7);ctx.stroke();}ctx.restore();ctx.fillStyle='#e9ecff';ctx.font='600 13px system-ui';ctx.textAlign='center';ctx.fillText(target==='sight'?`SIGHT · ${hz} Hz`:`GUARD · ${hz} Hz`,pos.x,pos.y+50);if(evidence>.02){ctx.fillStyle='rgba(255,255,255,.15)';ctx.fillRect(pos.x-28,pos.y+57,56,5);ctx.fillStyle=color==='blue'?'#55a3ff':'#55efa5';ctx.fillRect(pos.x-28,pos.y+57,56*evidence,5);}}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);if(state.t<state.guardUntil){ctx.strokeStyle='rgba(74,239,157,.65)';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,0,31,0,TAU);ctx.stroke();}ctx.fillStyle='#e9ecff';ctx.beginPath();ctx.arc(0,0,player.r,0,TAU);ctx.fill();ctx.fillStyle='#7c86d5';ctx.beginPath();ctx.moveTo(10,-12);ctx.lineTo(29,0);ctx.lineTo(10,12);ctx.closePath();ctx.fill();ctx.restore();}
function drawBoss(){if(!boss.alive)return;const pulse=.5+.5*Math.sin(state.t*(2+boss.phase));ctx.save();ctx.translate(boss.x,boss.y);ctx.fillStyle=`rgba(${90+boss.phase*22},65,150,.95)`;ctx.beginPath();ctx.arc(0,0,boss.r,0,TAU);ctx.fill();ctx.strokeStyle=`rgba(210,190,255,${.35+.35*pulse})`;ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,boss.r+8+pulse*5,0,TAU);ctx.stroke();ctx.fillStyle='#f0ebff';ctx.font='800 18px system-ui';ctx.textAlign='center';ctx.fillText('THE FRACTURED SIGNAL',0,6);ctx.restore();}
function drawProjectiles(){ctx.fillStyle=state.t<state.sightUntil?'#5aa8ff':'#f5f6ff';for(const s of state.shots){ctx.beginPath();ctx.arc(s.x,s.y,state.t<state.sightUntil?7:5,0,TAU);ctx.fill();}ctx.fillStyle='#ff657d';for(const s of state.enemyShots){ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,TAU);ctx.fill();}}
function drawParticles(){for(const p of state.particles){const a=clamp(p.life/p.max,0,1),c=p.kind==='blue'?`rgba(78,165,255,${a})`:p.kind==='green'?`rgba(72,240,157,${a})`:p.kind==='red'?`rgba(255,91,112,${a})`:`rgba(245,247,255,${a})`;ctx.fillStyle=c;ctx.beginPath();ctx.arc(p.x,p.y,3,0,TAU);ctx.fill();}}
function drawHud(){ctx.textAlign='left';ctx.font='700 15px system-ui';ctx.fillStyle='#eef0ff';ctx.fillText('GUARDIAN',34,38);ctx.fillStyle='rgba(255,255,255,.14)';ctx.fillRect(34,48,240,12);ctx.fillStyle='#55efa5';ctx.fillRect(34,48,240*player.hp/player.maxHp,12);ctx.fillStyle='#eef0ff';ctx.fillText(`HP ${Math.ceil(player.hp)}`,34,82);ctx.textAlign='center';ctx.fillText(boss.alive?`FRACTURED SIGNAL · PHASE ${boss.phase}`:'SIGNAL RESTORED',W/2,38);ctx.fillStyle='rgba(255,255,255,.14)';ctx.fillRect(W/2-220,48,440,10);ctx.fillStyle='#ad77ff';ctx.fillRect(W/2-220,48,440*boss.hp/boss.maxHp,10);const s=Math.max(0,state.sightUntil-state.t),g=Math.max(0,state.guardUntil-state.t);ctx.textAlign='right';ctx.fillStyle=s>0?'#61acff':'#777d9f';ctx.fillText(`SIGHT ×${cfg.sightMultiplier.toFixed(2)} ${s.toFixed(1)}s`,W-34,38);ctx.fillStyle=g>0?'#5cf2a5':'#777d9f';ctx.fillText(`GUARD +${cfg.guardHealPerSecond.toFixed(1)} HP/s ${g.toFixed(1)}s`,W-34,62);}
function render(){drawBackground();drawWisp();drawBoss();if(boss.alive&&state.started){drawAura('sight','blue',cfg.blueHz,auraPosition('sight'),state.sightUntil,state.blueEvidence);drawAura('guard','green',cfg.greenHz,auraPosition('guard'),state.guardUntil,state.greenEvidence);}drawPlayer();drawProjectiles();drawParticles();drawHud();}
function updateTelemetry(){blueMeter.value=state.blueEvidence;greenMeter.value=state.greenEvidence;blueValue.textContent=state.blueEvidence.toFixed(2);greenValue.textContent=state.greenEvidence.toFixed(2);if(state.started&&state.t>=state.sightUntil&&state.t>=state.guardUntil&&!state.bciTarget)neuralState.textContent='READY';}
let last=performance.now();function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(state.started){state.t+=dt;updateEvidence(dt);updatePlayer(dt);updateBoss(dt);updateProjectiles(dt);updateParticles(dt);updateTelemetry();}render();requestAnimationFrame(frame);}window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','q','e',' ','shift'].includes(k))e.preventDefault();keys.add(k);if(e.key==='Shift')dash();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));startButton.addEventListener('click',()=>{state.started=true;intro.classList.add('hidden');neuralState.textContent='READY';lastEvent.textContent='WISP_LINKED';});requestAnimationFrame(frame);
})();
